import 'dotenv/config';
import pg from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);

const clientMod = await import('../src/generated/prisma/client.ts');
const { PrismaClient } = clientMod.default || clientMod;
const prisma = new PrismaClient({ adapter });

const cars = [
  // ─── Iranian Cars ─────────────────────────────────
  { nameEn: "Iran Khodro Tara", nameFa: "تارا", brand: "IKCO", brandFa: "ایران‌خودرو", category: "sedan", year: 1403, priceMin: 1500000000n, priceMax: 2000000000n, origin: "iranian", description: "سدان جدید ایران‌خودرو با طراحی مدرن و امکانات به‌روز", tags: ["شهری", "اقتصادی", "داخلی"], scores: { comfort: 6, performance: 5, economy: 7, safety: 5, prestige: 5, reliability: 5, resaleValue: 7, familyFriendly: 6, sportiness: 4, offroad: 2, cityDriving: 7, longTrip: 5, maintenanceRisk: 5, afterSales: 5 }, specs: { engine: "1.65L", horsepower: 122, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 7.5, seatingCapacity: 5 } },
  { nameEn: "Iran Khodro Dena Plus Turbo", nameFa: "دنا پلاس توربو", brand: "IKCO", brandFa: "ایران‌خودرو", category: "sedan", year: 1403, priceMin: 1600000000n, priceMax: 2100000000n, origin: "iranian", description: "سدان توربوی ایران‌خودرو با موتور قدرتمند و فضای داخلی مناسب", tags: ["شهری", "قدرتمند", "داخلی"], scores: { comfort: 6, performance: 6, economy: 6, safety: 5, prestige: 5, reliability: 5, resaleValue: 7, familyFriendly: 6, sportiness: 5, offroad: 2, cityDriving: 7, longTrip: 5, maintenanceRisk: 5, afterSales: 5 }, specs: { engine: "1.65L Turbo", horsepower: 150, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.0, seatingCapacity: 5 } },
  { nameEn: "SAIPA Shahin", nameFa: "شاهین", brand: "SAIPA", brandFa: "سایپا", category: "sedan", year: 1403, priceMin: 1500000000n, priceMax: 1800000000n, origin: "iranian", description: "سدان جدید سایپا با طراحی اروپایی و قیمت مناسب", tags: ["اقتصادی", "شهری", "داخلی"], scores: { comfort: 5, performance: 5, economy: 7, safety: 5, prestige: 4, reliability: 5, resaleValue: 6, familyFriendly: 5, sportiness: 4, offroad: 2, cityDriving: 7, longTrip: 4, maintenanceRisk: 5, afterSales: 4 }, specs: { engine: "1.5L", horsepower: 111, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 7.0, seatingCapacity: 5 } },
  { nameEn: "SAIPA Quick R", nameFa: "کوییک آر", brand: "SAIPA", brandFa: "سایپا", category: "hatchback", year: 1403, priceMin: 1500000000n, priceMax: 1700000000n, origin: "iranian", description: "هاچبک اسپرت سایپا با تیراژ بالا و قطعات در دسترس", tags: ["اقتصادی", "شهری", "جوان‌پسند"], scores: { comfort: 4, performance: 5, economy: 8, safety: 4, prestige: 3, reliability: 5, resaleValue: 6, familyFriendly: 3, sportiness: 5, offroad: 1, cityDriving: 8, longTrip: 3, maintenanceRisk: 4, afterSales: 4 }, specs: { engine: "1.5L", horsepower: 111, transmission: "manual", fuelType: "gasoline", fuelConsumption: 6.5, seatingCapacity: 5 } },
  { nameEn: "Iran Khodro Peugeot 207i", nameFa: "پژو ۲۰۷ آی", brand: "IKCO", brandFa: "ایران‌خودرو", category: "hatchback", year: 1403, priceMin: 1500000000n, priceMax: 1900000000n, origin: "iranian", description: "هاچبک محبوب با طراحی فرانسوی و عملکرد شهری عالی", tags: ["شهری", "جوان‌پسند", "محبوب"], scores: { comfort: 5, performance: 5, economy: 7, safety: 5, prestige: 5, reliability: 5, resaleValue: 7, familyFriendly: 4, sportiness: 5, offroad: 2, cityDriving: 8, longTrip: 4, maintenanceRisk: 5, afterSales: 5 }, specs: { engine: "1.6L TU5", horsepower: 117, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 7.5, seatingCapacity: 5 } },
  { nameEn: "Iran Khodro Haima S7 Turbo", nameFa: "هایما S7 توربو", brand: "IKCO", brandFa: "ایران‌خودرو", category: "suv", year: 1403, priceMin: 2200000000n, priceMax: 2800000000n, origin: "iranian", description: "شاسی‌بلند خانوادگی با موتور توربو و فضای داخلی بزرگ", tags: ["خانوادگی", "شاسی‌بلند", "قدرتمند"], scores: { comfort: 7, performance: 6, economy: 5, safety: 6, prestige: 6, reliability: 5, resaleValue: 6, familyFriendly: 8, sportiness: 4, offroad: 5, cityDriving: 5, longTrip: 7, maintenanceRisk: 6, afterSales: 5 }, specs: { engine: "1.8L Turbo", horsepower: 177, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 9.5, seatingCapacity: 5 } },
  { nameEn: "Iran Khodro Haima S8", nameFa: "هایما S8", brand: "IKCO", brandFa: "ایران‌خودرو", category: "suv", year: 1403, priceMin: 2800000000n, priceMax: 3500000000n, origin: "iranian", description: "شاسی‌بلند لوکس ایران‌خودرو با امکانات کامل و طراحی مدرن", tags: ["لوکس", "خانوادگی", "شاسی‌بلند"], scores: { comfort: 8, performance: 7, economy: 4, safety: 7, prestige: 7, reliability: 5, resaleValue: 6, familyFriendly: 8, sportiness: 5, offroad: 5, cityDriving: 5, longTrip: 8, maintenanceRisk: 6, afterSales: 5 }, specs: { engine: "1.8L Turbo", horsepower: 177, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 10.0, seatingCapacity: 7 } },
  { nameEn: "SAIPA Rira", nameFa: "ریرا", brand: "SAIPA", brandFa: "سایپا", category: "crossover", year: 1403, priceMin: 2000000000n, priceMax: 2500000000n, origin: "iranian", description: "کراس‌اوور جدید سایپا با طراحی جذاب و امکانات مناسب", tags: ["شاسی‌بلند", "جوان‌پسند", "جدید"], scores: { comfort: 6, performance: 5, economy: 6, safety: 5, prestige: 5, reliability: 4, resaleValue: 5, familyFriendly: 6, sportiness: 4, offroad: 4, cityDriving: 6, longTrip: 5, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.6L Turbo", horsepower: 150, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 5 } },
  { nameEn: "Iran Khodro Peugeot Pars", nameFa: "پژو پارس", brand: "IKCO", brandFa: "ایران‌خودرو", category: "sedan", year: 1402, priceMin: 1500000000n, priceMax: 1700000000n, origin: "iranian", description: "سدان کلاسیک و پرطرفدار با قطعات فراوان و نقدشوندگی بالا", tags: ["اقتصادی", "پرطرفدار", "قطعات فراوان"], scores: { comfort: 5, performance: 4, economy: 7, safety: 4, prestige: 4, reliability: 6, resaleValue: 8, familyFriendly: 5, sportiness: 3, offroad: 2, cityDriving: 7, longTrip: 5, maintenanceRisk: 4, afterSales: 6 }, specs: { engine: "1.8L XU7", horsepower: 120, transmission: "manual", fuelType: "gasoline", fuelConsumption: 9.0, seatingCapacity: 5 } },
  { nameEn: "Iran Khodro Samand Soren", nameFa: "سمند سورن پلاس", brand: "IKCO", brandFa: "ایران‌خودرو", category: "sedan", year: 1402, priceMin: 1500000000n, priceMax: 1700000000n, origin: "iranian", description: "سدان اقتصادی با هزینه نگهداری پایین و بازار خوب", tags: ["اقتصادی", "کم‌هزینه", "قطعات فراوان"], scores: { comfort: 5, performance: 4, economy: 8, safety: 4, prestige: 3, reliability: 6, resaleValue: 7, familyFriendly: 5, sportiness: 3, offroad: 2, cityDriving: 6, longTrip: 5, maintenanceRisk: 4, afterSales: 6 }, specs: { engine: "1.8L XU7", horsepower: 120, transmission: "manual", fuelType: "gasoline", fuelConsumption: 9.5, seatingCapacity: 5 } },
  // ─── Chinese Cars ─────────────────────────────────
  { nameEn: "MVM X33 S", nameFa: "ام‌وی‌ام X33 S", brand: "MVM", brandFa: "ام‌وی‌ام", category: "crossover", year: 1403, priceMin: 2000000000n, priceMax: 2500000000n, origin: "chinese", description: "کراس‌اوور چینی با امکانات خوب و قیمت رقابتی", tags: ["شاسی‌بلند", "امکانات خوب", "چینی"], scores: { comfort: 6, performance: 5, economy: 6, safety: 5, prestige: 5, reliability: 5, resaleValue: 5, familyFriendly: 6, sportiness: 4, offroad: 4, cityDriving: 6, longTrip: 5, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 147, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 8.0, seatingCapacity: 5 } },
  { nameEn: "MVM X55 Pro", nameFa: "ام‌وی‌ام X55 پرو", brand: "MVM", brandFa: "ام‌وی‌ام", category: "suv", year: 1403, priceMin: 2500000000n, priceMax: 3200000000n, origin: "chinese", description: "شاسی‌بلند پرامکانات با فضای داخلی بزرگ و طراحی شیک", tags: ["خانوادگی", "پرامکانات", "شاسی‌بلند"], scores: { comfort: 7, performance: 6, economy: 5, safety: 6, prestige: 6, reliability: 5, resaleValue: 5, familyFriendly: 8, sportiness: 4, offroad: 5, cityDriving: 5, longTrip: 7, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 155, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 9.0, seatingCapacity: 5 } },
  { nameEn: "Chery Tiggo 7 Pro", nameFa: "تیگو ۷ پرو", brand: "Chery", brandFa: "چری", category: "suv", year: 1403, priceMin: 3000000000n, priceMax: 3800000000n, origin: "chinese", description: "شاسی‌بلند لوکس چری با تکنولوژی پیشرفته و طراحی مدرن", tags: ["لوکس", "پرامکانات", "شاسی‌بلند"], scores: { comfort: 8, performance: 7, economy: 5, safety: 7, prestige: 7, reliability: 5, resaleValue: 5, familyFriendly: 7, sportiness: 5, offroad: 5, cityDriving: 6, longTrip: 7, maintenanceRisk: 6, afterSales: 5 }, specs: { engine: "1.5L Turbo", horsepower: 155, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 5 } },
  { nameEn: "Chery Tiggo 8 Pro", nameFa: "تیگو ۸ پرو", brand: "Chery", brandFa: "چری", category: "suv", year: 1403, priceMin: 3500000000n, priceMax: 4500000000n, origin: "chinese", description: "شاسی‌بلند ۷ نفره با موتور قوی و فضای بسیار بزرگ", tags: ["خانوادگی", "۷ نفره", "لوکس"], scores: { comfort: 8, performance: 7, economy: 4, safety: 7, prestige: 7, reliability: 5, resaleValue: 5, familyFriendly: 9, sportiness: 4, offroad: 5, cityDriving: 4, longTrip: 8, maintenanceRisk: 7, afterSales: 5 }, specs: { engine: "1.6L Turbo", horsepower: 197, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 10.0, seatingCapacity: 7 } },
  { nameEn: "Chery Arrizo 6 Pro", nameFa: "آریزو ۶ پرو", brand: "Chery", brandFa: "چری", category: "sedan", year: 1403, priceMin: 2200000000n, priceMax: 2800000000n, origin: "chinese", description: "سدان اسپرت چری با طراحی جذاب و امکانات رفاهی بالا", tags: ["اسپرت", "جوان‌پسند", "شیک"], scores: { comfort: 7, performance: 6, economy: 6, safety: 6, prestige: 6, reliability: 5, resaleValue: 5, familyFriendly: 5, sportiness: 6, offroad: 2, cityDriving: 7, longTrip: 6, maintenanceRisk: 5, afterSales: 5 }, specs: { engine: "1.5L Turbo", horsepower: 147, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 7.5, seatingCapacity: 5 } },
  { nameEn: "Fownix FX", nameFa: "فونیکس FX", brand: "SAIPA", brandFa: "سایپا", category: "crossover", year: 1403, priceMin: 2200000000n, priceMax: 2800000000n, origin: "chinese", description: "کراس‌اوور مدرن با طراحی اروپایی و امکانات فناورانه", tags: ["شاسی‌بلند", "مدرن", "خوش‌ظاهر"], scores: { comfort: 7, performance: 6, economy: 5, safety: 6, prestige: 6, reliability: 4, resaleValue: 4, familyFriendly: 6, sportiness: 5, offroad: 4, cityDriving: 6, longTrip: 6, maintenanceRisk: 7, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 150, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 5 } },
  { nameEn: "KMC J7", nameFa: "کی‌ام‌سی J7", brand: "KMC", brandFa: "کرمان‌موتور", category: "suv", year: 1403, priceMin: 2500000000n, priceMax: 3200000000n, origin: "chinese", description: "شاسی‌بلند کرمان‌موتور با ظاهر متفاوت و فضای داخلی خوب", tags: ["شاسی‌بلند", "خانوادگی", "متفاوت"], scores: { comfort: 7, performance: 6, economy: 5, safety: 6, prestige: 5, reliability: 5, resaleValue: 4, familyFriendly: 7, sportiness: 4, offroad: 5, cityDriving: 5, longTrip: 6, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 150, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 9.0, seatingCapacity: 5 } },
  { nameEn: "KMC K7", nameFa: "کی‌ام‌سی K7", brand: "KMC", brandFa: "کرمان‌موتور", category: "suv", year: 1403, priceMin: 3000000000n, priceMax: 4000000000n, origin: "chinese", description: "شاسی‌بلند بزرگ با امکانات لوکس و موتور توربو", tags: ["لوکس", "شاسی‌بلند", "بزرگ"], scores: { comfort: 8, performance: 7, economy: 4, safety: 6, prestige: 7, reliability: 5, resaleValue: 4, familyFriendly: 8, sportiness: 4, offroad: 5, cityDriving: 4, longTrip: 7, maintenanceRisk: 7, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 174, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 10.0, seatingCapacity: 7 } },
  { nameEn: "BAIC X55", nameFa: "بایک X55", brand: "BAIC", brandFa: "بایک", category: "crossover", year: 1403, priceMin: 2200000000n, priceMax: 2800000000n, origin: "chinese", description: "کراس‌اوور خوش‌قیمت با امکانات مناسب و طراحی ساده", tags: ["اقتصادی", "شاسی‌بلند", "خوش‌قیمت"], scores: { comfort: 6, performance: 5, economy: 6, safety: 5, prestige: 4, reliability: 5, resaleValue: 4, familyFriendly: 6, sportiness: 3, offroad: 4, cityDriving: 6, longTrip: 5, maintenanceRisk: 6, afterSales: 3 }, specs: { engine: "1.5L Turbo", horsepower: 150, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 5 } },
  { nameEn: "Dongfeng AX7", nameFa: "دانگ‌فنگ AX7", brand: "Dongfeng", brandFa: "دانگ‌فنگ", category: "suv", year: 1403, priceMin: 2800000000n, priceMax: 3500000000n, origin: "chinese", description: "شاسی‌بلند پرامکانات با فضای وسیع و طراحی جدید", tags: ["خانوادگی", "شاسی‌بلند", "پرامکانات"], scores: { comfort: 7, performance: 6, economy: 5, safety: 6, prestige: 6, reliability: 5, resaleValue: 4, familyFriendly: 7, sportiness: 4, offroad: 5, cityDriving: 5, longTrip: 7, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 167, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 9.0, seatingCapacity: 5 } },
  { nameEn: "Changan CS35 Plus", nameFa: "چانگان CS35 پلاس", brand: "Changan", brandFa: "چانگان", category: "crossover", year: 1403, priceMin: 2000000000n, priceMax: 2600000000n, origin: "chinese", description: "کراس‌اوور کامپکت با طراحی جوان‌پسند و مصرف مناسب", tags: ["جوان‌پسند", "شهری", "شاسی‌بلند"], scores: { comfort: 6, performance: 5, economy: 6, safety: 5, prestige: 5, reliability: 5, resaleValue: 4, familyFriendly: 5, sportiness: 5, offroad: 3, cityDriving: 7, longTrip: 5, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.4L Turbo", horsepower: 158, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 7.5, seatingCapacity: 5 } },
  { nameEn: "Changan CS55 Plus", nameFa: "چانگان CS55 پلاس", brand: "Changan", brandFa: "چانگان", category: "suv", year: 1403, priceMin: 2800000000n, priceMax: 3500000000n, origin: "chinese", description: "شاسی‌بلند خوش‌ساخت با امکانات رفاهی بالا و طراحی مدرن", tags: ["خانوادگی", "پرامکانات", "شاسی‌بلند"], scores: { comfort: 7, performance: 6, economy: 5, safety: 6, prestige: 6, reliability: 5, resaleValue: 4, familyFriendly: 7, sportiness: 4, offroad: 4, cityDriving: 5, longTrip: 7, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 181, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 9.0, seatingCapacity: 5 } },
  { nameEn: "Haval H6", nameFa: "هاوال H6", brand: "Haval", brandFa: "هاوال", category: "suv", year: 1403, priceMin: 3200000000n, priceMax: 4000000000n, origin: "chinese", description: "شاسی‌بلند پرفروش جهانی با کیفیت ساخت بالا و امکانات لوکس", tags: ["لوکس", "خانوادگی", "باکیفیت"], scores: { comfort: 8, performance: 7, economy: 5, safety: 7, prestige: 7, reliability: 6, resaleValue: 5, familyFriendly: 8, sportiness: 5, offroad: 5, cityDriving: 5, longTrip: 8, maintenanceRisk: 5, afterSales: 5 }, specs: { engine: "1.5L Turbo", horsepower: 169, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 5 } },
  { nameEn: "Haval Jolion", nameFa: "هاوال جولیان", brand: "Haval", brandFa: "هاوال", category: "crossover", year: 1403, priceMin: 2500000000n, priceMax: 3200000000n, origin: "chinese", description: "کراس‌اوور شیک با امکانات فناورانه و طراحی جوان‌پسند", tags: ["جوان‌پسند", "شیک", "فناورانه"], scores: { comfort: 7, performance: 6, economy: 6, safety: 6, prestige: 6, reliability: 5, resaleValue: 5, familyFriendly: 6, sportiness: 5, offroad: 4, cityDriving: 7, longTrip: 6, maintenanceRisk: 5, afterSales: 5 }, specs: { engine: "1.5L Turbo", horsepower: 150, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.0, seatingCapacity: 5 } },
  { nameEn: "GAC GS3", nameFa: "جک GS3", brand: "GAC", brandFa: "جک", category: "crossover", year: 1403, priceMin: 2200000000n, priceMax: 2800000000n, origin: "chinese", description: "کراس‌اوور کامپکت با قیمت مناسب و امکانات قابل‌قبول", tags: ["اقتصادی", "شهری", "شاسی‌بلند"], scores: { comfort: 6, performance: 5, economy: 6, safety: 5, prestige: 5, reliability: 5, resaleValue: 4, familyFriendly: 5, sportiness: 4, offroad: 3, cityDriving: 7, longTrip: 5, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 163, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.0, seatingCapacity: 5 } },
  { nameEn: "Lifan X70", nameFa: "لیفان X70", brand: "Lifan", brandFa: "لیفان", category: "suv", year: 1402, priceMin: 2000000000n, priceMax: 2700000000n, origin: "chinese", description: "شاسی‌بلند خوش‌قیمت با فضای داخلی مناسب", tags: ["اقتصادی", "خانوادگی", "خوش‌قیمت"], scores: { comfort: 6, performance: 5, economy: 6, safety: 5, prestige: 4, reliability: 4, resaleValue: 3, familyFriendly: 6, sportiness: 3, offroad: 4, cityDriving: 5, longTrip: 5, maintenanceRisk: 7, afterSales: 3 }, specs: { engine: "1.8L", horsepower: 130, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 9.0, seatingCapacity: 5 } },
  // ─── Korean Cars ──────────────────────────────────
  { nameEn: "Hyundai Tucson", nameFa: "هیوندای توسان", brand: "Hyundai", brandFa: "هیوندای", category: "suv", year: 2024, priceMin: 3500000000n, priceMax: 5000000000n, origin: "korean", description: "شاسی‌بلند محبوب کره‌ای با طراحی آینده‌نگرانه و کیفیت بالا", tags: ["لوکس", "خانوادگی", "بادوام", "محبوب"], scores: { comfort: 9, performance: 7, economy: 6, safety: 8, prestige: 8, reliability: 8, resaleValue: 8, familyFriendly: 8, sportiness: 5, offroad: 6, cityDriving: 6, longTrip: 9, maintenanceRisk: 4, afterSales: 7 }, specs: { engine: "2.0L", horsepower: 156, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 5 } },
  { nameEn: "Hyundai Santa Fe", nameFa: "هیوندای سانتافه", brand: "Hyundai", brandFa: "هیوندای", category: "suv", year: 2024, priceMin: 4500000000n, priceMax: 5000000000n, origin: "korean", description: "شاسی‌بلند بزرگ و لوکس هیوندای با فضای ۷ نفره و امکانات کامل", tags: ["لوکس", "۷ نفره", "خانوادگی", "بادوام"], scores: { comfort: 9, performance: 7, economy: 5, safety: 9, prestige: 9, reliability: 8, resaleValue: 8, familyFriendly: 9, sportiness: 4, offroad: 6, cityDriving: 4, longTrip: 9, maintenanceRisk: 4, afterSales: 7 }, specs: { engine: "2.4L", horsepower: 185, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 10.5, seatingCapacity: 7 } },
  { nameEn: "Hyundai Sonata", nameFa: "هیوندای سوناتا", brand: "Hyundai", brandFa: "هیوندای", category: "sedan", year: 2024, priceMin: 3500000000n, priceMax: 4500000000n, origin: "korean", description: "سدان بزرگ و باکلاس با طراحی مدرن و عملکرد عالی", tags: ["لوکس", "باکلاس", "راحت"], scores: { comfort: 9, performance: 7, economy: 6, safety: 8, prestige: 8, reliability: 8, resaleValue: 7, familyFriendly: 7, sportiness: 6, offroad: 1, cityDriving: 7, longTrip: 9, maintenanceRisk: 3, afterSales: 7 }, specs: { engine: "2.0L", horsepower: 156, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.0, seatingCapacity: 5 } },
  { nameEn: "Hyundai Elantra", nameFa: "هیوندای النترا", brand: "Hyundai", brandFa: "هیوندای", category: "sedan", year: 2024, priceMin: 2800000000n, priceMax: 3800000000n, origin: "korean", description: "سدان محبوب کره‌ای با طراحی جسورانه و مصرف بهینه", tags: ["جوان‌پسند", "شیک", "محبوب"], scores: { comfort: 8, performance: 7, economy: 7, safety: 8, prestige: 7, reliability: 8, resaleValue: 8, familyFriendly: 6, sportiness: 6, offroad: 1, cityDriving: 8, longTrip: 7, maintenanceRisk: 3, afterSales: 7 }, specs: { engine: "2.0L", horsepower: 147, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 7.0, seatingCapacity: 5 } },
  { nameEn: "KIA Sportage", nameFa: "کیا اسپورتیج", brand: "KIA", brandFa: "کیا", category: "suv", year: 2024, priceMin: 3800000000n, priceMax: 5000000000n, origin: "korean", description: "شاسی‌بلند محبوب با طراحی جدید، امنیت بالا و نقدشوندگی عالی", tags: ["لوکس", "محبوب", "امن", "خانوادگی"], scores: { comfort: 9, performance: 7, economy: 6, safety: 9, prestige: 8, reliability: 8, resaleValue: 9, familyFriendly: 8, sportiness: 5, offroad: 6, cityDriving: 6, longTrip: 9, maintenanceRisk: 3, afterSales: 7 }, specs: { engine: "2.0L", horsepower: 156, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 5 } },
  { nameEn: "KIA Cerato", nameFa: "کیا سراتو", brand: "KIA", brandFa: "کیا", category: "sedan", year: 2024, priceMin: 2800000000n, priceMax: 3800000000n, origin: "korean", description: "سدان کره‌ای با نقدشوندگی عالی، کیفیت ساخت بالا و قطعات مناسب", tags: ["محبوب", "بادوام", "نقدشونده"], scores: { comfort: 8, performance: 7, economy: 7, safety: 8, prestige: 7, reliability: 8, resaleValue: 9, familyFriendly: 7, sportiness: 5, offroad: 1, cityDriving: 8, longTrip: 7, maintenanceRisk: 3, afterSales: 7 }, specs: { engine: "2.0L", horsepower: 150, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 7.5, seatingCapacity: 5 } },
  { nameEn: "KIA Sorento", nameFa: "کیا سورنتو", brand: "KIA", brandFa: "کیا", category: "suv", year: 2024, priceMin: 4500000000n, priceMax: 5000000000n, origin: "korean", description: "شاسی‌بلند ۷ نفره لوکس با قدرت بالا و امکانات کامل", tags: ["لوکس", "۷ نفره", "قدرتمند", "خانوادگی"], scores: { comfort: 9, performance: 8, economy: 5, safety: 9, prestige: 9, reliability: 8, resaleValue: 8, familyFriendly: 9, sportiness: 5, offroad: 7, cityDriving: 4, longTrip: 9, maintenanceRisk: 4, afterSales: 7 }, specs: { engine: "2.4L", horsepower: 185, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 10.0, seatingCapacity: 7 } },
  // ─── Japanese Cars ────────────────────────────────
  { nameEn: "Toyota RAV4", nameFa: "تویوتا راو۴", brand: "Toyota", brandFa: "تویوتا", category: "suv", year: 2024, priceMin: 4000000000n, priceMax: 5000000000n, origin: "japanese", description: "شاسی‌بلند افسانه‌ای ژاپنی با بالاترین اعتمادپذیری و نقدشوندگی", tags: ["بادوام", "افسانه‌ای", "نقدشونده", "خانوادگی"], scores: { comfort: 8, performance: 7, economy: 7, safety: 9, prestige: 8, reliability: 10, resaleValue: 10, familyFriendly: 8, sportiness: 4, offroad: 7, cityDriving: 6, longTrip: 9, maintenanceRisk: 2, afterSales: 7 }, specs: { engine: "2.5L", horsepower: 203, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.0, seatingCapacity: 5 } },
  { nameEn: "Toyota Corolla", nameFa: "تویوتا کرولا", brand: "Toyota", brandFa: "تویوتا", category: "sedan", year: 2024, priceMin: 3000000000n, priceMax: 4000000000n, origin: "japanese", description: "سدان پرفروش‌ترین خودروی جهان با قابلیت اطمینان بی‌نظیر", tags: ["بادوام", "اقتصادی", "مطمئن", "محبوب"], scores: { comfort: 7, performance: 6, economy: 8, safety: 8, prestige: 7, reliability: 10, resaleValue: 9, familyFriendly: 7, sportiness: 4, offroad: 1, cityDriving: 8, longTrip: 7, maintenanceRisk: 1, afterSales: 7 }, specs: { engine: "1.8L", horsepower: 139, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 6.5, seatingCapacity: 5 } },
  { nameEn: "Toyota C-HR", nameFa: "تویوتا C-HR", brand: "Toyota", brandFa: "تویوتا", category: "crossover", year: 2024, priceMin: 3500000000n, priceMax: 4500000000n, origin: "japanese", description: "کراس‌اوور اسپرت تویوتا با طراحی خاص و مصرف پایین", tags: ["اسپرت", "خاص", "کم‌مصرف"], scores: { comfort: 7, performance: 6, economy: 8, safety: 8, prestige: 7, reliability: 9, resaleValue: 8, familyFriendly: 5, sportiness: 7, offroad: 3, cityDriving: 8, longTrip: 6, maintenanceRisk: 2, afterSales: 7 }, specs: { engine: "1.8L Hybrid", horsepower: 122, transmission: "CVT", fuelType: "hybrid", fuelConsumption: 4.5, seatingCapacity: 5 } },
  { nameEn: "Mitsubishi Outlander", nameFa: "میتسوبیشی اوتلندر", brand: "Mitsubishi", brandFa: "میتسوبیشی", category: "suv", year: 2024, priceMin: 3800000000n, priceMax: 5000000000n, origin: "japanese", description: "شاسی‌بلند ۷ نفره با دیفرانسیل قفل‌شونده و مناسب جاده خاکی", tags: ["آفرود", "خانوادگی", "۷ نفره", "بادوام"], scores: { comfort: 7, performance: 7, economy: 5, safety: 8, prestige: 7, reliability: 8, resaleValue: 7, familyFriendly: 8, sportiness: 4, offroad: 8, cityDriving: 4, longTrip: 8, maintenanceRisk: 4, afterSales: 6 }, specs: { engine: "2.4L", horsepower: 167, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 9.5, seatingCapacity: 7 } },
  { nameEn: "Mitsubishi ASX", nameFa: "میتسوبیشی ASX", brand: "Mitsubishi", brandFa: "میتسوبیشی", category: "crossover", year: 2024, priceMin: 3000000000n, priceMax: 3800000000n, origin: "japanese", description: "کراس‌اوور کامپکت ژاپنی با ساخت محکم و مناسب شهر و جاده", tags: ["بادوام", "شهری", "همه‌کاره"], scores: { comfort: 7, performance: 6, economy: 6, safety: 7, prestige: 6, reliability: 8, resaleValue: 7, familyFriendly: 6, sportiness: 4, offroad: 5, cityDriving: 7, longTrip: 7, maintenanceRisk: 3, afterSales: 6 }, specs: { engine: "2.0L", horsepower: 150, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 8.0, seatingCapacity: 5 } },
  { nameEn: "Mazda 3", nameFa: "مزدا ۳", brand: "Mazda", brandFa: "مزدا", category: "sedan", year: 2024, priceMin: 3200000000n, priceMax: 4200000000n, origin: "japanese", description: "سدان اسپرت ژاپنی با طراحی زیبا و لذت رانندگی بالا", tags: ["اسپرت", "خوش‌ساخت", "جوان‌پسند"], scores: { comfort: 8, performance: 7, economy: 7, safety: 8, prestige: 8, reliability: 8, resaleValue: 7, familyFriendly: 5, sportiness: 8, offroad: 1, cityDriving: 8, longTrip: 7, maintenanceRisk: 3, afterSales: 6 }, specs: { engine: "2.0L Skyactiv", horsepower: 155, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 6.5, seatingCapacity: 5 } },
  { nameEn: "Mazda CX-5", nameFa: "مزدا CX-5", brand: "Mazda", brandFa: "مزدا", category: "suv", year: 2024, priceMin: 4000000000n, priceMax: 5000000000n, origin: "japanese", description: "شاسی‌بلند اسپرت با بهترین حس رانندگی در کلاس خود", tags: ["اسپرت", "لوکس", "خوش‌دست"], scores: { comfort: 8, performance: 8, economy: 6, safety: 8, prestige: 8, reliability: 8, resaleValue: 8, familyFriendly: 7, sportiness: 7, offroad: 4, cityDriving: 7, longTrip: 8, maintenanceRisk: 3, afterSales: 6 }, specs: { engine: "2.5L Skyactiv", horsepower: 187, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 5 } },
  { nameEn: "Nissan X-Trail", nameFa: "نیسان ایکس‌تریل", brand: "Nissan", brandFa: "نیسان", category: "suv", year: 2024, priceMin: 3800000000n, priceMax: 5000000000n, origin: "japanese", description: "شاسی‌بلند خانوادگی نیسان با فضای وسیع و سیستم ایمنی پیشرفته", tags: ["خانوادگی", "امن", "راحت"], scores: { comfort: 8, performance: 6, economy: 6, safety: 8, prestige: 7, reliability: 8, resaleValue: 7, familyFriendly: 8, sportiness: 4, offroad: 5, cityDriving: 6, longTrip: 8, maintenanceRisk: 3, afterSales: 6 }, specs: { engine: "2.5L", horsepower: 171, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 8.5, seatingCapacity: 7 } },
  { nameEn: "Honda CR-V", nameFa: "هوندا CR-V", brand: "Honda", brandFa: "هوندا", category: "suv", year: 2024, priceMin: 4000000000n, priceMax: 5000000000n, origin: "japanese", description: "شاسی‌بلند اسطوره‌ای با بهترین موتور و قابلیت اطمینان", tags: ["بادوام", "لوکس", "اسطوره‌ای"], scores: { comfort: 8, performance: 7, economy: 7, safety: 9, prestige: 8, reliability: 9, resaleValue: 9, familyFriendly: 8, sportiness: 4, offroad: 5, cityDriving: 6, longTrip: 9, maintenanceRisk: 2, afterSales: 6 }, specs: { engine: "1.5L Turbo", horsepower: 190, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 7.5, seatingCapacity: 5 } },
  // ─── More Cars ────────────────────────────────────
  { nameEn: "Peugeot 2008", nameFa: "پژو ۲۰۰۸", brand: "Peugeot", brandFa: "پژو", category: "crossover", year: 2018, priceMin: 2800000000n, priceMax: 3500000000n, origin: "european", description: "کراس‌اوور فرانسوی با طراحی شیک و کابین خاص", tags: ["شیک", "اروپایی", "خاص"], scores: { comfort: 7, performance: 6, economy: 6, safety: 7, prestige: 7, reliability: 6, resaleValue: 6, familyFriendly: 5, sportiness: 5, offroad: 3, cityDriving: 8, longTrip: 6, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "1.6L Turbo", horsepower: 163, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 7.0, seatingCapacity: 5 } },
  { nameEn: "Renault Koleos", nameFa: "رنو کولئوس", brand: "Renault", brandFa: "رنو", category: "suv", year: 2018, priceMin: 3500000000n, priceMax: 4500000000n, origin: "european", description: "شاسی‌بلند لوکس فرانسوی با فضای داخلی بسیار بزرگ و راحت", tags: ["لوکس", "اروپایی", "راحت"], scores: { comfort: 9, performance: 6, economy: 5, safety: 7, prestige: 8, reliability: 6, resaleValue: 5, familyFriendly: 8, sportiness: 3, offroad: 5, cityDriving: 5, longTrip: 8, maintenanceRisk: 6, afterSales: 4 }, specs: { engine: "2.5L", horsepower: 171, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 9.5, seatingCapacity: 5 } },
  { nameEn: "BYD Song Plus", nameFa: "بی‌وای‌دی سانگ پلاس", brand: "BYD", brandFa: "بی‌وای‌دی", category: "suv", year: 1403, priceMin: 3500000000n, priceMax: 4500000000n, origin: "chinese", description: "شاسی‌بلند هیبریدی با تکنولوژی پیشرفته و مصرف فوق‌العاده پایین", tags: ["هیبرید", "فناورانه", "کم‌مصرف"], scores: { comfort: 8, performance: 8, economy: 9, safety: 7, prestige: 7, reliability: 5, resaleValue: 5, familyFriendly: 7, sportiness: 6, offroad: 4, cityDriving: 9, longTrip: 7, maintenanceRisk: 6, afterSales: 3 }, specs: { engine: "1.5L Hybrid", horsepower: 218, transmission: "automatic", fuelType: "hybrid", fuelConsumption: 3.0, seatingCapacity: 5 } },
  { nameEn: "BYD Atto 3", nameFa: "بی‌وای‌دی آتو ۳", brand: "BYD", brandFa: "بی‌وای‌دی", category: "crossover", year: 1403, priceMin: 3000000000n, priceMax: 4000000000n, origin: "chinese", description: "کراس‌اوور تمام‌الکتریک با طراحی مدرن و عملکرد سبز", tags: ["الکتریکی", "فناورانه", "مدرن"], scores: { comfort: 8, performance: 8, economy: 10, safety: 7, prestige: 7, reliability: 5, resaleValue: 4, familyFriendly: 6, sportiness: 7, offroad: 3, cityDriving: 9, longTrip: 5, maintenanceRisk: 5, afterSales: 3 }, specs: { engine: "Electric", horsepower: 204, transmission: "automatic", fuelType: "electric", fuelConsumption: 0, seatingCapacity: 5 } },
  { nameEn: "Geely Emgrand", nameFa: "جیلی امگرند", brand: "Geely", brandFa: "جیلی", category: "sedan", year: 1403, priceMin: 1800000000n, priceMax: 2300000000n, origin: "chinese", description: "سدان چینی خوش‌قیمت با امکانات مناسب و طراحی ساده", tags: ["اقتصادی", "خوش‌قیمت", "شهری"], scores: { comfort: 6, performance: 5, economy: 7, safety: 5, prestige: 4, reliability: 5, resaleValue: 4, familyFriendly: 6, sportiness: 3, offroad: 1, cityDriving: 7, longTrip: 5, maintenanceRisk: 5, afterSales: 4 }, specs: { engine: "1.5L", horsepower: 114, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 7.0, seatingCapacity: 5 } },
  { nameEn: "Geely Coolray", nameFa: "جیلی کولری", brand: "Geely", brandFa: "جیلی", category: "crossover", year: 1403, priceMin: 2500000000n, priceMax: 3200000000n, origin: "chinese", description: "کراس‌اوور اسپرت با طراحی ولوو و عملکرد شهری عالی", tags: ["اسپرت", "جوان‌پسند", "شیک"], scores: { comfort: 7, performance: 7, economy: 6, safety: 6, prestige: 6, reliability: 5, resaleValue: 5, familyFriendly: 5, sportiness: 7, offroad: 3, cityDriving: 8, longTrip: 6, maintenanceRisk: 5, afterSales: 4 }, specs: { engine: "1.5L Turbo", horsepower: 177, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 7.5, seatingCapacity: 5 } },
  { nameEn: "Hyundai Accent", nameFa: "هیوندای اکسنت", brand: "Hyundai", brandFa: "هیوندای", category: "sedan", year: 2024, priceMin: 2200000000n, priceMax: 3000000000n, origin: "korean", description: "سدان کامپکت کره‌ای با قیمت مناسب و کیفیت ساخت خوب", tags: ["اقتصادی", "کره‌ای", "مناسب"], scores: { comfort: 7, performance: 6, economy: 8, safety: 7, prestige: 6, reliability: 8, resaleValue: 8, familyFriendly: 6, sportiness: 4, offroad: 1, cityDriving: 8, longTrip: 6, maintenanceRisk: 3, afterSales: 7 }, specs: { engine: "1.6L", horsepower: 123, transmission: "automatic", fuelType: "gasoline", fuelConsumption: 6.5, seatingCapacity: 5 } },
  { nameEn: "Honda Civic", nameFa: "هوندا سیویک", brand: "Honda", brandFa: "هوندا", category: "sedan", year: 2024, priceMin: 3500000000n, priceMax: 4500000000n, origin: "japanese", description: "سدان اسپرت ژاپنی با شهرت جهانی و لذت رانندگی بالا", tags: ["اسپرت", "بادوام", "جوان‌پسند"], scores: { comfort: 7, performance: 8, economy: 7, safety: 8, prestige: 8, reliability: 9, resaleValue: 8, familyFriendly: 5, sportiness: 8, offroad: 1, cityDriving: 7, longTrip: 7, maintenanceRisk: 2, afterSales: 6 }, specs: { engine: "1.5L Turbo", horsepower: 180, transmission: "CVT", fuelType: "gasoline", fuelConsumption: 6.5, seatingCapacity: 5 } },
];

async function main() {
  console.log("Seeding Mashinchi database...\n");

  await prisma.carTag.deleteMany();
  await prisma.carReview.deleteMany();
  await prisma.priceHistory.deleteMany();
  await prisma.userInteraction.deleteMany();
  await prisma.userTasteProfile.deleteMany();
  await prisma.user.deleteMany();
  await prisma.carScores.deleteMany();
  await prisma.carSpecs.deleteMany();
  await prisma.car.deleteMany();

  console.log("Cleaned existing data\n");

  for (const carData of cars) {
    const car = await prisma.car.create({
      data: {
        nameEn: carData.nameEn,
        nameFa: carData.nameFa,
        brand: carData.brand,
        brandFa: carData.brandFa,
        category: carData.category,
        year: carData.year,
        priceMin: carData.priceMin,
        priceMax: carData.priceMax,
        origin: carData.origin,
        description: carData.description,
        scores: { create: carData.scores },
        specs: { create: carData.specs },
        tags: { create: carData.tags.map((tag) => ({ tag })) },
      },
    });
    console.log(`  ${car.nameFa} (${car.nameEn})`);
  }

  console.log(`\nSeeded ${cars.length} cars successfully!`);
}

main()
  .catch((e) => { console.error("Seed error:", e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
